# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

from nautilus_trader import model

__all__ = [
    "BSE_VENUE",
    "GROWW",
    "GROWW_CLIENT_ID",
    "MCX_VENUE",
    "NSE_VENUE",
    "GrowwDataClientConfig",
    "GrowwDataClientFactory",
    "GrowwExecClientConfig",
    "GrowwExecutionClientFactory",
]

GROWW: str
GROWW_CLIENT_ID: model.ClientId
NSE_VENUE: model.Venue
BSE_VENUE: model.Venue
MCX_VENUE: model.Venue

@typing.final
class GrowwDataClientConfig:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        http_timeout_secs: int | None = None,
        exchanges: typing.Sequence[str] | None = None,
        segments: typing.Sequence[str] | None = None,
        instrument_types: typing.Sequence[str] | None = None,
    ) -> None: ...

@typing.final
class GrowwDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class GrowwExecClientConfig:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        http_timeout_secs: int | None = None,
        account_id: model.AccountId | None = None,
        product: str | None = None,
        exchanges: typing.Sequence[str] | None = None,
        segments: typing.Sequence[str] | None = None,
    ) -> None: ...

@typing.final
class GrowwExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
