// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! Market data feed types.
//!
//! @generated by prost-build from `proto/stocks_socket_response.proto`. Do not edit by hand;
//! see `proto/README.md` to regenerate.

// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BookProto {
    #[prost(double, tag = "1")]
    pub price: f64,
    #[prost(double, tag = "2")]
    pub qty: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StocksLivePriceProto {
    #[prost(double, tag = "1")]
    pub ts_in_millis: f64,
    #[prost(double, tag = "2")]
    pub open: f64,
    #[prost(double, tag = "3")]
    pub high: f64,
    #[prost(double, tag = "4")]
    pub low: f64,
    #[prost(double, tag = "5")]
    pub close: f64,
    #[prost(double, tag = "6")]
    pub volume: f64,
    #[prost(double, tag = "7")]
    pub value: f64,
    #[prost(double, tag = "8")]
    pub bid_qty: f64,
    #[prost(double, tag = "9")]
    pub offer_qty: f64,
    #[prost(double, tag = "10")]
    pub avg_price: f64,
    #[prost(double, tag = "11")]
    pub high_price_range: f64,
    #[prost(double, tag = "12")]
    pub low_price_range: f64,
    #[prost(double, tag = "13")]
    pub ltp: f64,
    #[prost(double, tag = "14")]
    pub open_interest: f64,
    #[prost(double, tag = "15")]
    pub low_trade_range: f64,
    #[prost(double, tag = "16")]
    pub high_trade_range: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StocksLiveIndicesProto {
    #[prost(double, tag = "1")]
    pub ts_in_millis: f64,
    #[prost(double, tag = "2")]
    pub value: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StocksMarketDepthProto {
    #[prost(double, tag = "1")]
    pub ts_in_millis: f64,
    #[prost(btree_map = "int32, message", tag = "2")]
    pub buy_book: ::prost::alloc::collections::BTreeMap<i32, BookProto>,
    #[prost(btree_map = "int32, message", tag = "3")]
    pub sell_book: ::prost::alloc::collections::BTreeMap<i32, BookProto>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StocksSocketResponseProtoDto {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(enumeration = "StockSegmentProto", tag = "2")]
    pub segment: i32,
    #[prost(enumeration = "StockExchangeProto", tag = "3")]
    pub exchange: i32,
    #[prost(message, optional, tag = "4")]
    pub stock_live_price: ::core::option::Option<StocksLivePriceProto>,
    #[prost(message, optional, tag = "5")]
    pub stocks_market_depth: ::core::option::Option<StocksMarketDepthProto>,
    #[prost(message, optional, tag = "6")]
    pub stocks_live_indices: ::core::option::Option<StocksLiveIndicesProto>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StocksMarketInfoProto {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StockExchangeProto {
    Bse = 0,
    Nse = 1,
    Mcx = 2,
    Mcxsx = 3,
    Ncdex = 4,
    Global = 5,
    Us = 6,
}
impl StockExchangeProto {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Bse => "BSE",
            Self::Nse => "NSE",
            Self::Mcx => "MCX",
            Self::Mcxsx => "MCXSX",
            Self::Ncdex => "NCDEX",
            Self::Global => "GLOBAL",
            Self::Us => "US",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BSE" => Some(Self::Bse),
            "NSE" => Some(Self::Nse),
            "MCX" => Some(Self::Mcx),
            "MCXSX" => Some(Self::Mcxsx),
            "NCDEX" => Some(Self::Ncdex),
            "GLOBAL" => Some(Self::Global),
            "US" => Some(Self::Us),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StockSegmentProto {
    Cash = 0,
    Fno = 1,
    Currency = 2,
    Commodity = 3,
}
impl StockSegmentProto {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Cash => "CASH",
            Self::Fno => "FNO",
            Self::Currency => "CURRENCY",
            Self::Commodity => "COMMODITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CASH" => Some(Self::Cash),
            "FNO" => Some(Self::Fno),
            "CURRENCY" => Some(Self::Currency),
            "COMMODITY" => Some(Self::Commodity),
            _ => None,
        }
    }
}
