// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! Order update feed types.
//!
//! @generated by prost-build from `proto/stock_orders_socket_response.proto`. Do not edit by hand;
//! see `proto/README.md` to regenerate.

// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StocksAmoStatus {}
/// Nested message and enum types in `StocksAmoStatus`.
pub mod stocks_amo_status {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        Na = 0,
        Pending = 1,
        Dispatched = 2,
        Parked = 3,
        Placed = 4,
        Failed = 5,
        Market = 6,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Na => "NA",
                Self::Pending => "PENDING",
                Self::Dispatched => "DISPATCHED",
                Self::Parked => "PARKED",
                Self::Placed => "PLACED",
                Self::Failed => "FAILED",
                Self::Market => "MARKET",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NA" => Some(Self::Na),
                "PENDING" => Some(Self::Pending),
                "DISPATCHED" => Some(Self::Dispatched),
                "PARKED" => Some(Self::Parked),
                "PLACED" => Some(Self::Placed),
                "FAILED" => Some(Self::Failed),
                "MARKET" => Some(Self::Market),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StocksOrderStatus {}
/// Nested message and enum types in `StocksOrderStatus`.
pub mod stocks_order_status {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        New = 0,
        Acked = 1,
        TriggerPending = 2,
        Approved = 3,
        Rejected = 4,
        Failed = 5,
        Executed = 6,
        DeliveryAwaited = 7,
        Cancelled = 8,
        CancellationRequested = 9,
        ModificationRequested = 10,
        Completed = 11,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::New => "NEW",
                Self::Acked => "ACKED",
                Self::TriggerPending => "TRIGGER_PENDING",
                Self::Approved => "APPROVED",
                Self::Rejected => "REJECTED",
                Self::Failed => "FAILED",
                Self::Executed => "EXECUTED",
                Self::DeliveryAwaited => "DELIVERY_AWAITED",
                Self::Cancelled => "CANCELLED",
                Self::CancellationRequested => "CANCELLATION_REQUESTED",
                Self::ModificationRequested => "MODIFICATION_REQUESTED",
                Self::Completed => "COMPLETED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NEW" => Some(Self::New),
                "ACKED" => Some(Self::Acked),
                "TRIGGER_PENDING" => Some(Self::TriggerPending),
                "APPROVED" => Some(Self::Approved),
                "REJECTED" => Some(Self::Rejected),
                "FAILED" => Some(Self::Failed),
                "EXECUTED" => Some(Self::Executed),
                "DELIVERY_AWAITED" => Some(Self::DeliveryAwaited),
                "CANCELLED" => Some(Self::Cancelled),
                "CANCELLATION_REQUESTED" => Some(Self::CancellationRequested),
                "MODIFICATION_REQUESTED" => Some(Self::ModificationRequested),
                "COMPLETED" => Some(Self::Completed),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StocksOrderDuration {}
/// Nested message and enum types in `StocksOrderDuration`.
pub mod stocks_order_duration {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        Ioc = 0,
        Day = 1,
        Gtd = 2,
        Gtc = 3,
        Eos = 4,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Ioc => "IOC",
                Self::Day => "DAY",
                Self::Gtd => "GTD",
                Self::Gtc => "GTC",
                Self::Eos => "EOS",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "IOC" => Some(Self::Ioc),
                "DAY" => Some(Self::Day),
                "GTD" => Some(Self::Gtd),
                "GTC" => Some(Self::Gtc),
                "EOS" => Some(Self::Eos),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StockExchange {}
/// Nested message and enum types in `StockExchange`.
pub mod stock_exchange {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        Bse = 0,
        Nse = 1,
        Mcx = 2,
        Mcxsx = 3,
        Ncdex = 4,
        Us = 5,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Bse => "BSE",
                Self::Nse => "NSE",
                Self::Mcx => "MCX",
                Self::Mcxsx => "MCXSX",
                Self::Ncdex => "NCDEX",
                Self::Us => "US",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "BSE" => Some(Self::Bse),
                "NSE" => Some(Self::Nse),
                "MCX" => Some(Self::Mcx),
                "MCXSX" => Some(Self::Mcxsx),
                "NCDEX" => Some(Self::Ncdex),
                "US" => Some(Self::Us),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StockSegment {}
/// Nested message and enum types in `StockSegment`.
pub mod stock_segment {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        Cash = 0,
        Fno = 1,
        Currency = 2,
        Commodity = 3,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Cash => "CASH",
                Self::Fno => "FNO",
                Self::Currency => "CURRENCY",
                Self::Commodity => "COMMODITY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CASH" => Some(Self::Cash),
                "FNO" => Some(Self::Fno),
                "CURRENCY" => Some(Self::Currency),
                "COMMODITY" => Some(Self::Commodity),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StocksProduct {}
/// Nested message and enum types in `StocksProduct`.
pub mod stocks_product {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        Cnc = 0,
        Mis = 1,
        Co = 2,
        Bo = 3,
        Nrml = 4,
        Arb = 5,
        Mtf = 6,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Cnc => "CNC",
                Self::Mis => "MIS",
                Self::Co => "CO",
                Self::Bo => "BO",
                Self::Nrml => "NRML",
                Self::Arb => "ARB",
                Self::Mtf => "MTF",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CNC" => Some(Self::Cnc),
                "MIS" => Some(Self::Mis),
                "CO" => Some(Self::Co),
                "BO" => Some(Self::Bo),
                "NRML" => Some(Self::Nrml),
                "ARB" => Some(Self::Arb),
                "MTF" => Some(Self::Mtf),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StocksOrderType {}
/// Nested message and enum types in `StocksOrderType`.
pub mod stocks_order_type {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        Mkt = 0,
        L = 1,
        Sl = 2,
        SlM = 3,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Mkt => "MKT",
                Self::L => "L",
                Self::Sl => "SL",
                Self::SlM => "SL_M",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "MKT" => Some(Self::Mkt),
                "L" => Some(Self::L),
                "SL" => Some(Self::Sl),
                "SL_M" => Some(Self::SlM),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StocksTransactionType {}
/// Nested message and enum types in `StocksTransactionType`.
pub mod stocks_transaction_type {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        Internal = 0,
        Pending = 1,
        Bonus = 2,
        BseBolt = 3,
        NseNow = 4,
        Ipo = 5,
        DematTransfer = 6,
        NestTerminal = 7,
        ExchangeShort = 8,
        Auction = 9,
        InternalShort = 10,
        Merger = 11,
        Fno = 12,
        BuyBack = 13,
        PhysicalSettlement = 14,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Internal => "INTERNAL",
                Self::Pending => "PENDING",
                Self::Bonus => "BONUS",
                Self::BseBolt => "BSE_BOLT",
                Self::NseNow => "NSE_NOW",
                Self::Ipo => "IPO",
                Self::DematTransfer => "DEMAT_TRANSFER",
                Self::NestTerminal => "NEST_TERMINAL",
                Self::ExchangeShort => "EXCHANGE_SHORT",
                Self::Auction => "AUCTION",
                Self::InternalShort => "INTERNAL_SHORT",
                Self::Merger => "MERGER",
                Self::Fno => "FNO",
                Self::BuyBack => "BUY_BACK",
                Self::PhysicalSettlement => "PHYSICAL_SETTLEMENT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "INTERNAL" => Some(Self::Internal),
                "PENDING" => Some(Self::Pending),
                "BONUS" => Some(Self::Bonus),
                "BSE_BOLT" => Some(Self::BseBolt),
                "NSE_NOW" => Some(Self::NseNow),
                "IPO" => Some(Self::Ipo),
                "DEMAT_TRANSFER" => Some(Self::DematTransfer),
                "NEST_TERMINAL" => Some(Self::NestTerminal),
                "EXCHANGE_SHORT" => Some(Self::ExchangeShort),
                "AUCTION" => Some(Self::Auction),
                "INTERNAL_SHORT" => Some(Self::InternalShort),
                "MERGER" => Some(Self::Merger),
                "FNO" => Some(Self::Fno),
                "BUY_BACK" => Some(Self::BuyBack),
                "PHYSICAL_SETTLEMENT" => Some(Self::PhysicalSettlement),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StocksBuySell {}
/// Nested message and enum types in `StocksBuySell`.
pub mod stocks_buy_sell {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        B = 0,
        S = 1,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::B => "B",
                Self::S => "S",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "B" => Some(Self::B),
                "S" => Some(Self::S),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StocksTradeStatus {}
/// Nested message and enum types in `StocksTradeStatus`.
pub mod stocks_trade_status {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        Executed = 0,
        DeliveryAwaited = 1,
        Completed = 2,
        Cancelled = 3,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Executed => "EXECUTED",
                Self::DeliveryAwaited => "DELIVERY_AWAITED",
                Self::Completed => "COMPLETED",
                Self::Cancelled => "CANCELLED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "EXECUTED" => Some(Self::Executed),
                "DELIVERY_AWAITED" => Some(Self::DeliveryAwaited),
                "COMPLETED" => Some(Self::Completed),
                "CANCELLED" => Some(Self::Cancelled),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrderSource {}
/// Nested message and enum types in `OrderSource`.
pub mod order_source {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Enum {
        User = 0,
        System = 1,
        Smallcase = 2,
        Smartorder = 3,
        Na = 4,
    }
    impl Enum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::User => "USER",
                Self::System => "SYSTEM",
                Self::Smallcase => "SMALLCASE",
                Self::Smartorder => "SMARTORDER",
                Self::Na => "NA",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "USER" => Some(Self::User),
                "SYSTEM" => Some(Self::System),
                "SMALLCASE" => Some(Self::Smallcase),
                "SMARTORDER" => Some(Self::Smartorder),
                "NA" => Some(Self::Na),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StageAndTimeStamp {
    #[prost(double, tag = "1")]
    pub time_stamp_from_mid_night: f64,
    #[prost(string, tag = "2")]
    pub stage_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderDetailsBroadCastDto {
    #[prost(message, repeated, tag = "1")]
    pub stage_and_time_stamp: ::prost::alloc::vec::Vec<StageAndTimeStamp>,
    #[prost(message, optional, tag = "2")]
    pub order_detail_update_dto: ::core::option::Option<OrderDetailUpdateDto>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrderDetailUpdateDto {
    #[prost(int32, tag = "1")]
    pub qty: i32,
    #[prost(int64, tag = "2")]
    pub price: i64,
    #[prost(int64, tag = "3")]
    pub trigger_price: i64,
    #[prost(int32, tag = "4")]
    pub filled_qty: i32,
    #[prost(int32, tag = "5")]
    pub remaining_qty: i32,
    #[prost(int64, tag = "6")]
    pub avg_fill_price: i64,
    #[prost(string, tag = "7")]
    pub groww_order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub exchange_order_id: ::prost::alloc::string::String,
    #[prost(enumeration = "stocks_order_status::Enum", tag = "9")]
    pub order_status: i32,
    #[prost(enumeration = "stocks_order_duration::Enum", tag = "10")]
    pub duration: i32,
    #[prost(enumeration = "stock_exchange::Enum", tag = "11")]
    pub exchange: i32,
    #[prost(enumeration = "stock_segment::Enum", tag = "12")]
    pub segment: i32,
    #[prost(enumeration = "stocks_product::Enum", tag = "13")]
    pub product: i32,
    #[prost(enumeration = "stocks_order_type::Enum", tag = "14")]
    pub order_type: i32,
    #[prost(enumeration = "stocks_buy_sell::Enum", tag = "15")]
    pub buy_sell: i32,
    #[prost(string, tag = "16")]
    pub remark: ::prost::alloc::string::String,
    #[prost(string, tag = "22")]
    pub contract_id: ::prost::alloc::string::String,
    #[prost(string, tag = "23")]
    pub gui_order_id: ::prost::alloc::string::String,
}
