// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! Position update feed types.
//!
//! @generated by prost-build from `proto/position_socket.proto`. Do not edit by hand;
//! see `proto/README.md` to regenerate.

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionDetailProto {
    #[prost(message, optional, tag = "1")]
    pub symbol_data: ::core::option::Option<SymbolInfoProto>,
    #[prost(message, optional, tag = "2")]
    pub position_info: ::core::option::Option<PositionInfoProto>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SymbolInfoProto {
    #[prost(int64, tag = "1")]
    pub tr_time_stamp: i64,
    #[prost(string, tag = "2")]
    pub search_id: ::prost::alloc::string::String,
    #[prost(enumeration = "StocksProduct", tag = "3")]
    pub stocks_product: i32,
    #[prost(string, tag = "4")]
    pub contract_id: ::prost::alloc::string::String,
    #[prost(enumeration = "EquityType", tag = "5")]
    pub equity_type: i32,
    #[prost(string, tag = "6")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub underlying_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub nse_market_lot: i64,
    #[prost(int64, tag = "9")]
    pub bse_market_lot: i64,
    #[prost(enumeration = "EquityAsset", tag = "10")]
    pub underlying_asset_type: i32,
    #[prost(int64, tag = "11")]
    pub freeze_qty: i64,
    #[prost(enumeration = "StockExchange", tag = "12")]
    pub exchange: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionInfoProto {
    #[prost(string, tag = "1")]
    pub symbol_isin: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub bse: ::core::option::Option<BseProto>,
    #[prost(message, optional, tag = "3")]
    pub nse: ::core::option::Option<NseProto>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BseProto {
    #[prost(double, tag = "1")]
    pub credit_qty: f64,
    #[prost(double, tag = "2")]
    pub credit_price: f64,
    #[prost(double, tag = "3")]
    pub debit_qty: f64,
    #[prost(double, tag = "4")]
    pub debit_price: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NseProto {
    #[prost(double, tag = "1")]
    pub credit_qty: f64,
    #[prost(double, tag = "2")]
    pub credit_price: f64,
    #[prost(double, tag = "3")]
    pub debit_qty: f64,
    #[prost(double, tag = "4")]
    pub debit_price: f64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StocksProduct {
    Cnc = 0,
    Mis = 1,
    Co = 2,
    Bo = 3,
    Nrml = 4,
    Arb = 5,
    Mtf = 6,
    Unknown = 7,
}
impl StocksProduct {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Cnc => "CNC",
            Self::Mis => "MIS",
            Self::Co => "CO",
            Self::Bo => "BO",
            Self::Nrml => "NRML",
            Self::Arb => "ARB",
            Self::Mtf => "MTF",
            Self::Unknown => "UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CNC" => Some(Self::Cnc),
            "MIS" => Some(Self::Mis),
            "CO" => Some(Self::Co),
            "BO" => Some(Self::Bo),
            "NRML" => Some(Self::Nrml),
            "ARB" => Some(Self::Arb),
            "MTF" => Some(Self::Mtf),
            "UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EquityType {
    Stocks = 0,
    Future = 1,
    Option = 2,
    Etf = 3,
    Index = 4,
    Bonds = 5,
}
impl EquityType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Stocks => "STOCKS",
            Self::Future => "FUTURE",
            Self::Option => "OPTION",
            Self::Etf => "ETF",
            Self::Index => "INDEX",
            Self::Bonds => "BONDS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STOCKS" => Some(Self::Stocks),
            "FUTURE" => Some(Self::Future),
            "OPTION" => Some(Self::Option),
            "ETF" => Some(Self::Etf),
            "INDEX" => Some(Self::Index),
            "BONDS" => Some(Self::Bonds),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EquityAsset {
    Stocks = 0,
    Indices = 1,
}
impl EquityAsset {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Stocks => "EQUITY_ASSET_STOCKS",
            Self::Indices => "EQUITY_ASSET_INDICES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EQUITY_ASSET_STOCKS" => Some(Self::Stocks),
            "EQUITY_ASSET_INDICES" => Some(Self::Indices),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StockExchange {
    Bse = 0,
    Nse = 1,
    Mcx = 2,
    Mcxsx = 3,
    Ncdex = 4,
    Global = 5,
    Us = 6,
}
impl StockExchange {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Bse => "BSE",
            Self::Nse => "NSE",
            Self::Mcx => "MCX",
            Self::Mcxsx => "MCXSX",
            Self::Ncdex => "NCDEX",
            Self::Global => "GLOBAL",
            Self::Us => "US",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BSE" => Some(Self::Bse),
            "NSE" => Some(Self::Nse),
            "MCX" => Some(Self::Mcx),
            "MCXSX" => Some(Self::Mcxsx),
            "NCDEX" => Some(Self::Ncdex),
            "GLOBAL" => Some(Self::Global),
            "US" => Some(Self::Us),
            _ => None,
        }
    }
}
